# -*- Mode: makefile-gmake -*-

EXE = TestFoilAuth
APP_SRC = FoilAuthToken.cpp
MOC_CPP = FoilAuth.cpp
MOC_H = FoilAuth.h

HARBOUR_SRC = \
  HarbourBase32.cpp

QRENCODE_SRC = \
  bitstream.c \
  mask.c \
  mmask.c \
  mqrspec.c \
  rsecc.c \
  split.c \
  qrencode.c \
  qrinput.c \
  qrspec.c

include ../Makefile.common
